[project]
name = "davai_taskutil"
dynamic = ["version"]
description = "Davai utilities for Davai/Vortex tasks."
readme = "README.md"
requires-python = ">=3.10"
keywords = []
license = {text = "CECILL-C"}
authors = [
    { name = "Alexandre Mary"  , email = "alexandre.mary@meteo.fr"}
    ]
dependencies=[
    "davai==1.2.0",
    "ial_build==1.3.3",
    "ial_expertise[all]==1.2.1",  # includes epygram
    "bronx",
    # indirect dependencies
    # from vortex:
    #"epygram==2.0.2",  #comes with ial_expertise, but hook_ts also needs it
    "requests[socks]",
    "jinja2",
    ]

[project.urls]
source = "https://github.com/ACCORD-NWP/DAVAI-tests.git"
tracker = "https://github.com/ACCORD-NWP/DAVAI-tests/issues"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
davai_taskutil = "src/davai_taskutil"
tasks = "src/tasks"

[tool.setuptools.dynamic]
version = {attr = "davai_taskutil.__version__"}

